# Generated by Django 2.2.4 on 2019-08-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
