# Generated by Django 2.2.4 on 2019-08-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20190817_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
