# Generated by Django 2.1.5 on 2019-08-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190806_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
