# Generated by Django 2.1.5 on 2019-08-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_medicine_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='tabletn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, max_length=1023, upload_to='images/'),
        ),
    ]
